require 'xively-rb/templates/json/feed_defaults'
require 'xively-rb/templates/json/datastream_defaults'
require 'xively-rb/templates/json/datapoint_defaults'
require 'xively-rb/templates/json/trigger_defaults'
require 'xively-rb/templates/json/search_result_defaults'
require 'xively-rb/templates/json/key_defaults'
