require 'xively-rb/parsers/json/feed_defaults'
require 'xively-rb/parsers/json/search_result_defaults'
require 'xively-rb/parsers/json/datastream_defaults'
require 'xively-rb/parsers/json/datapoint_defaults'
require 'xively-rb/parsers/json/trigger_defaults'
require 'xively-rb/parsers/json/key_defaults'
